set -s escape-time 0

# Remap prefix from C-b to C-a (easier to reach)
unbind C-b
set -g prefix C-a
bind-key C-a send-prefix

# Reload config
bind u source-file ~/.config/tmux/tmux.conf \; display-message "Reloaded config"

# Hotkeys for creating panes
bind "|" split-window -h -c "#{pane_current_path}"
bind "\\" split-window -fh -c "#{pane_current_path}"
bind "-" split-window -v -c "#{pane_current_path}"
bind "_" split-window -fv -c "#{pane_current_path}"

# Use mouse to scroll
set -g mouse on
set -g default-terminal "tmux-256color"

# Color current window
set-window-option -g window-status-current-style bg=red
set -g status-style bg=#333333

# Increase # of characters for a session name
set -g status-left-length 30

# Start index at 1
set -g base-index 1
setw -g pane-base-index 1

# Move bar to top
set -g status-position top

# New session
bind S command-prompt -p "New Session:" "new-session -A -s '%%'"
bind K confirm kill-session

# tmux-sensible settings
set -g history-limit 50000
set -g display-time 3000
set -g status-interval 10

# vim-tmux-navigator
vim_pattern='g?(view|n?vim?x?)(diff)?|fzf'
is_vim="echo '#{pane_current_command}' | grep -iqE '^(${vim_pattern})$'"
bind-key -n 'C-h' if-shell "$is_vim" 'send-keys C-h'  'select-pane -L'
bind-key -n 'C-j' if-shell "$is_vim" 'send-keys C-j'  'select-pane -D'
bind-key -n 'C-k' if-shell "$is_vim" 'send-keys C-k'  'select-pane -U'
bind-key -n 'C-l' if-shell "$is_vim" 'send-keys C-l'  'select-pane -R'
tmux_version='$(tmux -V | sed -En "s/^tmux ([0-9]+(.[0-9]+)?).*/\1/p")'
if-shell -b '[ "$(echo "$tmux_version < 3.0" | bc)" = 1 ]' \
    "bind-key -n 'C-\\' if-shell \"$is_vim\" 'send-keys C-\\'  'select-pane -l'"
if-shell -b '[ "$(echo "$tmux_version >= 3.0" | bc)" = 1 ]' \
    "bind-key -n 'C-\\' if-shell \"$is_vim\" 'send-keys C-\\\\'  'select-pane -l'"

bind-key -T copy-mode-vi 'C-h' select-pane -L
bind-key -T copy-mode-vi 'C-j' select-pane -D
bind-key -T copy-mode-vi 'C-k' select-pane -U
bind-key -T copy-mode-vi 'C-l' select-pane -R
bind-key -T copy-mode-vi 'C-\' select-pane -l
