# For vim, this makes ESC not lag
set -s escape-time 0

bind u source-file $XDG_CONFIG_HOME/tmux/tmux.conf \; display "Reloaded config"

unbind C-b
set -g prefix C-a
bind C-a send-prefix

set -g mouse on
set -g renumber-windows on
set -g default-terminal "tmux-256color"
set -g status-position top
set -g base-index 1
set -g pane-base-index 1
set -g status-left-length 30
set -g history-limit 50000
set -g display-time 3000
set -g status-interval 10

set-window-option -g window-status-current-style bg=red
set -g status-style bg=#333333

bind "\\" split-window -hc "#{pane_current_path}"
bind "|" split-window -fhc "#{pane_current_path}"
bind "-" split-window -vc "#{pane_current_path}"
bind "_" split-window -fvc "#{pane_current_path}"

bind S command-prompt -p "New Session:" "new-session -A -s '%%'"
bind K confirm kill-session

##### vim-tmux integration #####
vim_pattern='g?(view|n?vim?x?)(diff)?|fzf'
is_vim="echo '#{pane_current_command}' | grep -iqE '^(${vim_pattern})$'"
bind-key -n 'C-h' if-shell "$is_vim" 'send-keys C-h'  'select-pane -L'
bind-key -n 'C-j' if-shell "$is_vim" 'send-keys C-j'  'select-pane -D'
bind-key -n 'C-k' if-shell "$is_vim" 'send-keys C-k'  'select-pane -U'
bind-key -n 'C-l' if-shell "$is_vim" 'send-keys C-l'  'select-pane -R'
tmux_version='$(tmux -V | sed -En "s/^tmux ([0-9]+(.[0-9]+)?).*/\1/p")'
if-shell -b '[ "$(echo "$tmux_version < 3.0" | bc)" = 1 ]' \
    "bind-key -n 'C-\\' if-shell \"$is_vim\" 'send-keys C-\\'  'select-pane -l'"
if-shell -b '[ "$(echo "$tmux_version >= 3.0" | bc)" = 1 ]' \
    "bind-key -n 'C-\\' if-shell \"$is_vim\" 'send-keys C-\\\\'  'select-pane -l'"

bind-key -T copy-mode-vi 'C-h' select-pane -L
bind-key -T copy-mode-vi 'C-j' select-pane -D
bind-key -T copy-mode-vi 'C-k' select-pane -U
bind-key -T copy-mode-vi 'C-l' select-pane -R
bind-key -T copy-mode-vi 'C-\' select-pane -l
#####
